name: Force Survival Mode
version: 0.1.0

pipeline:
  - beet.contrib.render

meta:
  render:
    data_pack:
      - "**"

data_pack:
  description: {"text":"Force Survival Mode\n1.13 - 1.21.11", "color":"gray"}
  pack_format: 4
  min_format: 4
  max_format: 94
  supported_formats:
    min_inclusive: 4
    max_inclusive: 94
  load: src/datapack
  overlays:
    - directory: v1_21
      min_format: 48
      max_format: 94
      formats:
        min_inclusive: 48
        max_inclusive: 94

output: build
