name: Force Survival Mode
version: 0.2.0

pipeline:
  - src.plugins.gamemode

meta:
  base_version: "1.13"
  overlay_versions:
    v1_21: "1.21"

data_pack:
  load: src/datapack
  description: {"text":"Force Survival Mode\n1.13 - 26.1", "color":"gray"}
  pack_format: 4
  min_format: 4
  max_format: 101
  supported_formats:
    min_inclusive: 4
    max_inclusive: 101
  overlays:
    - directory: v1_21
      min_format: 48
      max_format: 101
      formats:
        min_inclusive: 48
        max_inclusive: 101

output: build
